remove fbcp

diff --git a/MHS35-varanda-show b/MHS35-varanda-show
--- a/MHS35-varanda-show
+++ b/MHS35-varanda-show
@@ -50,44 +50,45 @@ sudo touch ./.have_installed
 echo "gpio:resistance:mhs35:90:${lcd_w}:${lcd_h}" > ./.have_installed
 
 sudo apt-get update
+
 #FBCP install
-wget --spider -q -o /dev/null --tries=1 -T 10 https://cmake.org/
-if [ $? -eq 0 ]; then
-sudo apt-get install cmake -y 2> error_output.txt
-result=`cat ./error_output.txt`
-echo -e "\033[31m$result\033[0m"
-grep -q "^E:" ./error_output.txt
-type cmake > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-sudo rm -rf rpi-fbcp
-wget --spider -q -o /dev/null --tries=1 -T 10 https://github.com
-if [ $? -eq 0 ]; then
-sudo git clone https://github.com/tasanakorn/rpi-fbcp
-if [ $? -ne 0 ]; then
-echo "download fbcp failed, copy native fbcp!!!"
-sudo cp -r ./usr/rpi-fbcp .
-fi
-else
-echo "bad network, copy native fbcp!!!"
-sudo cp -r ./usr/rpi-fbcp .
-fi
-sudo mkdir ./rpi-fbcp/build
-cd ./rpi-fbcp/build/
-sudo cmake ..
-sudo make
-sudo install fbcp /usr/local/bin/fbcp
-cd - > /dev/null
-type fbcp > /dev/null 2>&1
-if [ $? -eq 0 ]; then
-sudo cp -rf ./usr/99-fbturbo-fbcp.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
-sudo cp -rf ./etc/rc.local /etc/rc.local
-fi
-else
-echo "install cmake error!!!!"
-fi
-else
-echo "bad network, can't install cmake!!!"
-fi
+# wget --spider -q -o /dev/null --tries=1 -T 10 https://cmake.org/
+# if [ $? -eq 0 ]; then
+# sudo apt-get install cmake -y 2> error_output.txt
+# result=`cat ./error_output.txt`
+# echo -e "\033[31m$result\033[0m"
+# grep -q "^E:" ./error_output.txt
+# type cmake > /dev/null 2>&1
+# if [ $? -eq 0 ]; then
+# sudo rm -rf rpi-fbcp
+# wget --spider -q -o /dev/null --tries=1 -T 10 https://github.com
+# if [ $? -eq 0 ]; then
+# sudo git clone https://github.com/tasanakorn/rpi-fbcp
+# if [ $? -ne 0 ]; then
+# echo "download fbcp failed, copy native fbcp!!!"
+# sudo cp -r ./usr/rpi-fbcp .
+# fi
+# else
+# echo "bad network, copy native fbcp!!!"
+# sudo cp -r ./usr/rpi-fbcp .
+# fi
+# sudo mkdir ./rpi-fbcp/build
+# cd ./rpi-fbcp/build/
+# sudo cmake ..
+# sudo make
+# sudo install fbcp /usr/local/bin/fbcp
+# cd - > /dev/null
+# type fbcp > /dev/null 2>&1
+# if [ $? -eq 0 ]; then
+# sudo cp -rf ./usr/99-fbturbo-fbcp.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
+# sudo cp -rf ./etc/rc.local /etc/rc.local
+# fi
+# else
+# echo "install cmake error!!!!"
+# fi
+# else
+# echo "bad network, can't install cmake!!!"
+# fi
 
 #evdev install
 #nodeplatform=`uname -n`
